### ISSUE TITLE
In mac_pro use eclipse import project error

### ISSUE THREAD

**Issue by ghost** [EsotericSoftware/spine-superspineboy#2]
Exception in thread "LWJGL Application" java.lang.NullPointerException
    at com.esotericsoftware.spine.superspineboy.Assets.<init>(Assets.java:70)
    at com.esotericsoftware.spine.superspineboy.View.<init>(View.java:98)
    at com.esotericsoftware.spine.superspineboy.SuperSpineboy.create(SuperSpineboy.java:51)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:136)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:114)

**Comment by NathanSweet** [comment]
I'm guessing `Gdx.audio` is null. Does OpenAL fail to initialize on your system? If you see "Couldn't initialize audio, disabling audio" in the console, it failed.

**Comment by NathanSweet** [comment]
Close for lack of feedback. Feel free to post more and if there is an issue to be had, we can reopen.
