### ISSUE TITLE
Mesh error! 

### ISSUE THREAD

**Issue by Demonwd** [EsotericSoftware/spine-superspineboy#3]
Model with mesh deform not working. Crash: FloatArray setSize error/

**Comment by NathanSweet** [comment]
Please post the entire error.

**Comment by Demonwd** [comment]
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: com.badlogic.gdx.utils.FloatArray.setSize(I)[F
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:131)
Caused by: java.lang.NoSuchMethodError: com.badlogic.gdx.utils.FloatArray.setSize(I)[F
    at Animation$DeformTimeline.apply(Animation.java:680)
    at Animation.mix(Animation.java:67)
    at AnimationState.apply(AnimationState.java:93)
    at PlayerView.update(PlayerView.java:83)
    at MapRenderer.render(MapRenderer.java:168)
    at GameScreen.render(GameScreen.java:25)
    at com.badlogic.gdx.Game.render(Game.java:46)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:223)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)

**Comment by X-Ray-Jin** [comment]
Hey I just came across that error too. It is exactly the same but maybe I can give some more information. Until now we used phyics editor to create our colliders with frame by frame animations. But now we completely switched to spine animations and wanted to try out the collider feature. So our animator added a collider which used deform. After replacing the animation ingame it crashes. I am not sure if it works without deform as I just recognized it. We will test that this week. Maybe it helps to know that we are not using mix animations so far and actually we didnt even add anything in the code to embed the colliders. We basically just use the simple animation features and events which work great. If you need more specific information please let me know. I am happy to provide anything that will help.

Thx for your great work.
Greetz

**Comment by NathanSweet** [comment]
NoSuchMethodError for `FloatArray.setSize` means your libgdx is out of date.

@X-Ray-Jin if your crash is the same, you just need to update your libgdx.
